### ISSUE TITLE
IntervalTree thread safety

### ISSUE THREAD

**Issue by eklinger** [Breinify/brein-time-utilities#3]
Hello, is the interval tree thread safe? It doesn't seem so but then what is the purpose of the atomic boolean being used in remove?

**Comment by pmeisen** [comment]
No the tree is not thread-safe. The `AtomicBoolean` is just used as convenience for a `byRef` parameter. You cannot pass in a `boolean` or a `Boolean` instead, and modify the value and read it outside the method (without returning it). Another alternative would be an array with the size of one, but that is kind of ugly.
