### ISSUE TITLE
Sorted Intervals

### ISSUE THREAD

**Issue by eklinger** [Breinify/brein-time-utilities#4]
Hi Phillipp,
Is there no way to traverse the tree in sorted order of the intervals? It doesn't seem like there is with an augmented interval tree but wanted to check with you. Thanks

**Comment by pmeisen** [comment]
It depends on what you call sorted. Does a `HashMap` return stored values (if you think about the hash function used it does). What sorting are you looking for? Like sorting by the start value, sorting by the end value, sorting by the range, sorting by insertion? There are many different types of things you sort by. In general, I would recommend to query for whatever you looking for (using overlap) and sort the returned set. If the set is to large to sort by, the `IntervalTree` may be the wrong data structure for your problem. You could have a second data structure, which contains your interval-identifiers in a sorted way. So if you actually need for example the top-n values you would use your one data-structure, but if you need to find overlaps, you use the `IntervalTree`. To see if there are any possibilities to utilize the `IntervalTree` and solve your sorting question, I would need further information, e.g., what are you sorting by, where is the problem to first query for overlaps and sort the data afterwards.

Best
Philipp

**Comment by eklinger** [comment]
I was interested in sort by start value

**Comment by pmeisen** [comment]
The `IntervalTree` does not support any sorting by start-value. So I would recommend to follow the approach I mentioned before, first get the intervals you are interested in and sort them afterwards according to your needs.
