### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by eklinger** [Breinify/brein-time-utilities#5]
Hello,
I am interested in making the interval tree thread-safe and wanted to get your feedback on the various approaches, feasibility, etc. For my case I will have many more readers than writers and writes will be infrequent compared to reads. 
1)  Seems like a ReadWriteLock might suffice here. Simply wrapping the modifying methods with a write lock and a read lock for the read methods. May lower throughput quite a bit depending upon thread contention.
2) Potentially a lock-free version could be achieved if you can find a serialization point/node in the tree under which the modification would take place and then separately rebuild that subtree and then use a CAS operation to update that node in the original tree. I'm not quite sure how the self-balancing aspect of the tree might affect this.

Are there any other ideas that might work? Have you had a need for thread safety in your own use?

Thanks again!

**Comment by pmeisen** [comment]
Hi,

that's a nice idea. Our operations on the tree are `thread-safe` already, so whenever the tree is modified we have thread-safety through other mechanism. So we didn't have the need to have the tree itself to be thread-safe. 

There are several approaches on how to achieve the safety. The first approach you mention sounds like a `Collections.synchronize` approach, in which you protect the appropriate methods against execution from multiple threads. If you would like to use multi-threading to increase performance, this probably won't do that much. If you just do it for the purpose of being thread-safe, that seems to be a good idea.

2. The self-balancing has effect on different sub-trees (which may be the whole tree, if the balancing if performed with the root). In general, there are several points in which the tree is modified, but the main question is, do you still want to query the tree while being in modification state, which would be difficult to achieve within performing a lock. 

I can have a more detailed look later today and let you know if I have any other ideas :).

**Comment by eklinger** [comment]
Can you share how are you achieving thread-safety now? 
The ReadWriteLock is different from synchronized in that it is not an exclusive lock - multiple readers can access the data at once whereas with synchronized they could not. 
Ideally reads can proceed while an update is also happening, hence the lock-free approach using CAS would probably be optimal.

**Comment by pmeisen** [comment]
> Can you share how are you achieving thread-safety now?

Sure we ensure in our system, that writes are synchronized, so that only one thread can actually modify the tree. If the tree is modified, there is no read access (like a `ReadWriteLock`). But we ensure that through our system already, so that we don't have the need to have that within the tree.

> The ReadWriteLock is different from synchronized in that it is not an exclusive lock - multiple readers can access the data at once whereas with synchronized they could not.

Yeah, got it.

> Ideally reads can proceed while an update is also happening, hence the lock-free approach using CAS would probably be optimal.

Yes, I think CAS would be a good approach, which would increase memory usage and also probably increase computation time, because you would have to create clones at some points. I will have a closer look.

**Comment by pmeisen** [comment]
Closed, no further progress.
