### ISSUE TITLE
IDInterval Comparing IDs

### ISSUE THREAD

**Issue by eklinger** [Breinify/brein-time-utilities#6]
Hi,
In com.brein.time.timeintervals.intervals.IdInterval.compareId(IdInterval), the method is using compareTo() to compare the ids. Should this be equals() instead? Thanks!

**Comment by pmeisen** [comment]
No it should not. It is a comparision and not checking for equality. The method returns a difference following the logic of the `Comparable` interface and not the logic of equality. See also the `Comparable` JavaDoc:

```
It is strongly recommended, but <i>not</i> strictly required that (x.compareTo(y)==0) == (x.equals(y)).  Generally speaking, any class that implements the Comparable interface and violates this condition should clearly indicate this fact.  The recommended language is "Note: this class has a natural ordering that is inconsistent with equals.
```

This is required, because the `IdInterval` implements `Comparable` and so does the `id`.

**Comment by eklinger** [comment]
Maybe I am abusing the IDInterval then? I am storing my full object and not just an ID, and my object implements Comparable to order them by start time since I also use the Collection sorting methods on them. But in the case when I call remove() from the tree it ends up comparing my ids by calling compareTo which is comparing by start date. So I could modify my compareTo to first compare by date and then by id, which should work, but seems a bit odd to me. I guess in this case I should create my own IInterval completely?

**Comment by pmeisen** [comment]
Yes I recommend to implement your own `IInterval` in this case. Intervals depend strongly on the `compareTo` implementation, so it should be implemented according to the use-case. If needed you can `extend` the `IdInterval` and just override the `compareTo` method.

**Comment by eklinger** [comment]
Hi,
The interval will always be compared with its start & end time first, correct? Then it will use my compareTo() in case of ties?
Thanks

**Comment by pmeisen** [comment]
To store the data in the `IntervalTree`, the only relevant value is the `start` and `end` value, i.e., these are the values that are compared to determine the `node` the data is stored in. Once the `node` is determined the actual `compareTo` of the `IInterval` may be used to determine if the data is held in the `node` (depending what type of container you are using in a node, e.g., if you are using an `ArrayList` the `compareTo` should never be called, but if you are, e.g., using a `HashSet` the `compareTo` will be utilized). 

see also: 
- [in-memory](https://github.com/Breinify/brein-time-utilities/blob/master/docs/StoreCachePersist.md#in-memory)
- [extending intervals](https://github.com/Breinify/brein-time-utilities/blob/master/docs/Interval.md#extending-intervals-and-what-to-consider)
