### ISSUE TITLE
Wrong interval relation

### ISSUE THREAD

**Issue by crypticmind** [Breinify/brein-time-utilities#7]
Hi,

The following code output `OVERLAPS` instead of the expected `AFTER`. What am I doing wrong?

```java
        LongInterval i1 = new LongInterval(1L, 5L);
        LongInterval i2 = new LongInterval(8L, 10L);
        System.out.println(i1.ir(i2));
```

I'm using version 1.6.2.

Thanks,
Carlos

**Comment by crypticmind** [comment]
Version 1.6.3 shows the same behaviour.

**Comment by pmeisen** [comment]
Hi crypticmind!

Thanks for the bug-report. It is fixed in the newest version `1.6.4`. The version will probably be available tomorrow (or earlier) on Maven Central.

Btw. the result should have been `BEFORE`  [1, 5] is before [8, 10].

**Comment by crypticmind** [comment]
Hi pmeisen,
Thanks for fix!
I see two commits after the 1.6.4 release that also seem relevant. Should I wait for 1.6.5?

**Comment by pmeisen** [comment]
Hi,

the release was tagged to early on Github (I just recreated the release with the right source code). The Maven deployment is based on the right code, so it is good to use 1.6.4.

Best,
Philipp

**Comment by crypticmind** [comment]
Thank you!
